DROP SCHEMA IF EXISTS dw CASCADE;
CREATE SCHEMA dw;


-- DIMENSION 1: COMPANHIA AÉREA (CARRIER)

CREATE TABLE dw.DIM_CRE (
    SRK_CRE SERIAL PRIMARY KEY,
    CRE_CDE VARCHAR(10) UNIQUE NOT NULL,
    CRE_NME VARCHAR(200)
);


-- DIMENSION 2: AEROPORTO

CREATE TABLE dw.DIM_ARR (
    SRK_ARR SERIAL PRIMARY KEY,
    ARR_CDE VARCHAR(10) UNIQUE NOT NULL,
    ARR_NME VARCHAR(200)
);


-- DIMENSION 3: TEMPO

CREATE TABLE dw.DIM_TME (
    SRK_TME SERIAL PRIMARY KEY,
    YAR INTEGER NOT NULL,
    MNH INTEGER NOT NULL,
    TIS INTEGER,
    SMT INTEGER,
    MES_NME VARCHAR(20),
    MES_ANO VARCHAR(7),
    ANO_TIS VARCHAR(7),
    UNIQUE(YAR, MNH)
);


-- FACT TABLE: ATRASOS DE VOOS

CREATE TABLE dw.FCT_FIT_DLS (
    SRK_FCT SERIAL PRIMARY KEY,
    SRK_CRE INTEGER NOT NULL,
    SRK_ARR INTEGER NOT NULL,
    SRK_TME INTEGER NOT NULL,
    
    -- métricas operacionais
    ARR_FIT DECIMAL(10,2),
    ARR_DEL DECIMAL(10,2),
    ARR_CNL DECIMAL(10,2),
    ARR_DVR DECIMAL(10,2),
    ARR_DLY DECIMAL(10,2),
    
    -- contagem de atrasos por causa
    CRE_CT DECIMAL(10,2),
    WAE_CT DECIMAL(10,2),
    NAS_CT DECIMAL(10,2),
    SCR_CT DECIMAL(10,2),
    LTE_ARA_CT DECIMAL(10,2),
    
    -- tempo de atraso por causa (minutos)
    CRE_DLY DECIMAL(10,2),
    WAE_DLY DECIMAL(10,2),
    NAS_DLY DECIMAL(10,2),
    SCR_DLY DECIMAL(10,2),
    LTE_ARA_DLY DECIMAL(10,2),
    
    -- métricas calculadas
    DLY_RTE DECIMAL(5,2),
    CNL_RTE DECIMAL(5,2),
    DVS_RTE DECIMAL(5,2),
    AVG_DLY_MNE DECIMAL(10,2),
    ONT_RTE DECIMAL(5,2),
    
    UNIQUE(SRK_CRE, SRK_ARR, SRK_TME),
    FOREIGN KEY (SRK_CRE) REFERENCES dw.DIM_CRE(SRK_CRE),
    FOREIGN KEY (SRK_ARR) REFERENCES dw.DIM_ARR(SRK_ARR),
    FOREIGN KEY (SRK_TME) REFERENCES dw.DIM_TME(SRK_TME)
);